apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
spec:
  releaseName: mysql
  chart:
    spec:
      chart: mysql
      sourceRef:
        kind: HelmRepository
        name: mysql
        namespace: flux-system
      version: "*"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: mysql-values
